#!/usr/bin/env bash

create_directories() {
    directories=(
        "~/dev"
        "~/Screenshots"
    )

    for directory in "${directories[@]}"; do
        if [ ! -d "$directory" ]; then
            mkdir -p "$directory"
        fi
    done
}

install_apt_packages() {
    packages=(
        "build-essential"
        "wget"
        "curl"
        "xclip"
        "vim"
        "cmake"
        "pkg-config"
        "python3"
        "scrot"
        "arandr"
        "python3-pip"
        "suckless-tools"
        "stow"
        "rofi"
        "fonts-firacode"
        "apt-transport-https"
        "autoconf"
        # playerctl is needed for i55blocks mediaplayer
        "playerctl"
    )

    for package in "${packages[@]}"; do
        if ! dpkg -s "$package" >/dev/null 2>&1; then
            sudo apt install -y "$package"
        fi
    done
}

install_i3xrocks_packages() {
    packages=(
        "i3xrocks-battery"
        "i3xrocks-memory"
        "i3xrocks-nm-vpn"
        "i3xrocks-volume"
    )

    for package in "${packages[@]}"; do
        if ! dpkg -s "$package" >/dev/null 2>&1; then
            sudo apt install -y "$package"
        fi
    done
}

install_fish() {
    sudo apt-add-repository ppa:fish-shell/release-3
    sudo apt update && sudo apt install -y fish

    chsh -s $(which fish)

    # Install Fisher - fish plugins
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

    fisher install PatrickF1/fzf.fish FabioAntunes/fish-nvm edc/bass
}

install_rush_and_cargo() {
    curl https://sh.rustup.rs -sSf | sh

    packages=(
        "alacritty"
        "bat"
        "exa"
        "ripgrep"
        "fd-find"
    )

    for package in "${packages[@]}"; do
        cargo install $package
    done
}

install_starship() {
    curl -sS https://starship.rs/install.sh | sh
}

install_python_packages() {
    packages=(
        "pulsectl"
    )

    for package in "${packages[@]}"; do
        pip3 install -U $package
    done
}

install_nvm() {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
}

set_regolith_looks() {
    sudo apt install -y regolith-look-nord
    regolith-look set nord
    regolith-look refresh
}

create_directories
install_apt_packages
install_i3xrocks_packages
install_fish
install_rush_and_cargo
install_starship
install_python_packages
install_nvm
set_regolith_looks

