#!/usr/bin/env bash

. ./bootstrap-scripts/apt-packages.sh
. ./bootstrap-scripts/fish.sh
. ./bootstrap-scripts/i3xrocks.sh
. ./bootstrap-scripts/nvm.sh
. ./bootstrap-scripts/rust.sh
. ./bootstrap-scripts/starship.sh

# Run regolith-looks last as the UI will flash
. ./bootstrap-scripts/regolith-looks.sh
