#!/usr/bin/env bash

create_directories() {
    directories=(
        "~/dev"
        "~/Screenshots"
    )

    for directory in "${directories[@]}"; do
        if [ ! -d "$directory" ]; then
            mkdir -p "$directory"
        fi
    done
}

install_apt_packages() {
    packages=(
        "build-essential"
        "wget"
        "curl"
        "xclip"
        "vim"
        "cmake"
        "pkg-config"
        "libfreetype6-dev"
        "libfontconfig1-dev"
        "libxcb-xfixes0-dev"
        "libxkbcommon-dev"
        "python3"
        "scrot"
        "arandr"
        "python3-pip"
        "suckless-tools"
        "stow"
        "rofi"
        "fonts-firacode"
        "apt-transport-https"

        #(i3status dependencies)
        "autoconf"
        "libconfuse-dev"
        "libyajl-dev"
        "libasound2-dev"
        "libiw-dev"
        "asciidoc"
        "libpulse-dev"
        "libnl-genl-3-dev"
        "meson"

        # playerctl is needed for i55blocks mediaplayer
        "playerctl"
    )

    for package in "${packages[@]}"; do
        if ! dpkg -s "$package" >/dev/null 2>&1; then
            sudo apt install -y "$package"
        fi
    done
}

install_fish() {
    sudo apt-add-repository ppa:fish-shell/release-3
    sudo apt update && sudo apt install -y fish

    chsh -s $(which fish)

    # Install Fisher - fish plugins
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

    fisher install PatrickF1/fzf.fish FabioAntunes/fish-nvm edc/bass
}

install_rush_and_cargo() {
    curl https://sh.rustup.rs -sSf | sh

    # Install cargo stuff:
    packages=(
        "alacritty"
        "bat"
        "exa"
        "ripgrep"
        "fd-find"
    )

    for package in "${packages[@]}"; do
        cargo install $package
    done
}

install_starship() {
    curl -sS https://starship.rs/install.sh | sh
}

install_python_packages() {
    packages=(
        "pulsectl"
    )
    for package in "${packages[@]}"; do
        pip3 install -U $package
    done
}

install_i3status() {
    git clone git@github.com:i3/i3status.git ~/dev/i3status
    cd ~/dev/i3status
    mkdir build
    cd build
    meson ..
    ninja
    sudo ninja install
}

install_nvm() {
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
}

install_vscode() {
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >packages.microsoft.gpg
    sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
    sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
    rm -f packages.microsoft.gpg
    sudo apt update && sudo apt install -y code
}

create_directories
install_apt_packages
install_fish
install_rush_and_cargo
install_starship
install_python_packages
install_i3status
install_nvm
install_vscode
