# Inserts a blank line between shell prompts
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✖](bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 3
truncation_symbol = ".../"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = " [$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_commit]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[ocaml]
disabled = true

[perl]
disabled = true

[rust]
disabled = true

[username]
style_user = "bold dimmed blue"
show_always = false

[scala]
disabled = true

[java]
disabled = true
